/* @name       compiler.d -- Provides information about the compiler used.
 * @author     Peter A. Biocini
 * @info       This module provides information about the compiler, since adlib
 *             is not distributed with the D compiler, we cannot put anything
 *             specific here. I'd like to plan ahead, so in the future I'd
 *             like to have this file generated at compiletime, or by a configure.
 *             script. Compilers should be able to return these types of attributes.
 */

// src/std/compiler.d
module std.compiler;

// Defining these variables as constant, as they will never be touched by any other modules.
const
{
    /* This string holds the specific compiler and it's Vendor, for example: "GDC"
     * maybe this should be changed to "compiler" in the future. */
    char[] name = "Generic"; // Defaults to Generic
    
    /* Enum that holds the list of all D compiler vendors.
     * This will likely be generated by a configure script in the future, 
     * but for now we will define the standard one as Generic */
    enum Vendor 
    {
        Generic = 1,
        DigitalMars,
        GDC
    }
    
    // Standard compiler vendor is Generic
    Vendor vendor = Vendor.Generic;
    
    /* We define a version number here in three variables instead of the two used in Phobos
     * The syntax is version_branch.version_major.version_minor, set to 0.0.0 by default. */
    uint version_branch = 0;
    uint version_major = 0;
    uint version_minor = 0;
    
    /* These two variables specify the version of the D Language Spec that is supported
     * in the form of D_major.D_minor */
    uint D_major = 0;
    uint D_minor = 0;
}
    
    